
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const Chat = lazy(() => import("./pages/Chat.tsx"));
const EditProfile = lazy(() => import("./pages/EditProfile.tsx"));
const Journal = lazy(() => import("./pages/Journal.tsx"));
const Progress = lazy(() => import("./pages/Progress.tsx"));
const SelfCare = lazy(() => import("./pages/SelfCare.tsx"));
const SelfCareActivity = lazy(() => import("./pages/SelfCareActivity.tsx"));
const Settings = lazy(() => import("./pages/Settings.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/chat", element: <UserGuard><Chat /></UserGuard>},
	{ path: "/edit-profile", element: <UserGuard><EditProfile /></UserGuard>},
	{ path: "/editprofile", element: <UserGuard><EditProfile /></UserGuard>},
	{ path: "/journal", element: <UserGuard><Journal /></UserGuard>},
	{ path: "/progress", element: <UserGuard><Progress /></UserGuard>},
	{ path: "/self-care", element: <UserGuard><SelfCare /></UserGuard>},
	{ path: "/selfcare", element: <UserGuard><SelfCare /></UserGuard>},
	{ path: "/self-care-activity", element: <UserGuard><SelfCareActivity /></UserGuard>},
	{ path: "/selfcareactivity", element: <UserGuard><SelfCareActivity /></UserGuard>},
	{ path: "/settings", element: <UserGuard><Settings /></UserGuard>},

];
